# Generated by Django 5.2.4 on 2025-08-01 12:24

import app.services.helpers.date_helper
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cnp', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)])),
                ('email', models.EmailField(max_length=254)),
                ('employee_code', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('IC', 'IC'), ('Manager', 'Manager')], default='IC')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Performance', 'Performance'), ('Holidays', 'Holidays'), ('Certification', 'Certification'), ('Referral', 'Referral'), ('Loyalty', 'Loyalty')], max_length=200, null=True)),
                ('month', models.DateField(default=app.services.helpers.date_helper.first_day_of_current_month)),
                ('value', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=app.services.helpers.date_helper.first_day_of_current_month)),
                ('base_value', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=app.services.helpers.date_helper.first_day_of_current_month)),
                ('working_days', models.IntegerField()),
                ('vacation_days', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday', to='app.employee')),
            ],
        ),
    ]
